### ISSUE TITLE
Backend route for registration

### ISSUE THREAD

**Issue by the-rooster** [UofA-Blueprint/AlzheimerCalgary#66]
Create a POST end point using HTTPS that receives a JSON object with the following format:

{
username : String,
role : String,
token: String
}

username - the name of the user to be created. username should have a minimum and maximum length. should consider if special characters are allowed in the username (non alphanum)
token - the user session token of the user creating the account. used to verify if the requester is a staff member or not
role - either caregiver or staff

the end point will return the following JSON object if the session token is valid:

{
username : String,
password : String
}
username - the name of the user that has been created
password - a password generated for this user that is to be given to the new user to log in and change their password

if the session token is not valid, return a HTTP status code of 400

**security constraints:**
STORING PASSWORD:

password field should be hashed + salted with AES or another modern hash standard.

to check if a password is valid, hash + salt the incoming password and compare to the one in the DB.

DB QUERIES:

use non injectable string formatting. i.e official mongodb string formatter of some kind

**TASKS**

- [x] JWT token verification + creation
- [x] Password generation
- [x] Password checking + secure password storage
- [x] Build the HTTPS endpoint
